# Generated by Django 4.1.5 on 2023-01-05 17:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("nax_guests", models.IntegerField()),
                ("n_bathrooms", models.IntegerField()),
                ("is_pet_friendly", models.BooleanField()),
                ("clean_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("activation_date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("airbnb", "AirBnb"),
                            ("booking", "Booking"),
                            ("seazone", "Seazone"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
