# Generated by Django 4.1.5 on 2023-01-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="nax_guests",
            new_name="max_guests",
        ),
    ]
