# Generated by Django 4.1.5 on 2023-01-05 17:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("checkin_date", models.DateField()),
                ("checkout_date", models.DateField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("n_guests", models.IntegerField()),
                ("comment", models.TextField(blank=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.announcement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
