# Generated by Django 4.1.5 on 2023-01-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
